### ISSUE TITLE
How to achieve token renewal？

### ISSUE THREAD

**Issue by meimosor** [m-thirumal/oauth-authorization-server#3]
Hi guys!When the client accessToken is about to expire, How to achieve token renewal？

Whether the token expires should be intercepted and judged at the backend, or should the interceptor be requested to do a Refresh Token request at the frontend？

Looking forward to your reply.

**Comment by m-thirumal** [comment]
I guess, you are talking about single page application (spa) / browser application. Check this article [https://curity.io/resources/learn/spa-best-practices/?utm_source=infoq&utm_medium=newsletter&utm_campaign=infoq](https://curity.io/resources/learn/spa-best-practices/?utm_source=infoq&utm_medium=newsletter&utm_campaign=infoq)
