### ISSUE TITLE
Refresh Token that never expires

### ISSUE THREAD

**Issue by meimosor** [m-thirumal/oauth-authorization-server#4]
When configuring refresh_token with a value of 0, an exception is thrown, and it does not work properly. Similarly, setting the token access scope value profile_offline_access prompts an incorrect scope. How can I correctly request a never-expiring refresh token ?
![image](https://user-images.githubusercontent.com/31975932/236597781-0e7a0920-b17f-4eac-8865-67b6a92df6c6.png)

![image](https://user-images.githubusercontent.com/31975932/236597799-bc3095e8-84d3-4056-bd64-097cb32c106d.png)

it seems doesn't work.
![image](https://user-images.githubusercontent.com/31975932/236597903-b3e0218c-62ea-4334-86b8-c2017a9ebe57.png)

**Comment by m-thirumal** [comment]
This feature is not available yet in the new authorization server.

You can set `Interger.MAX` in token setting
